public-awesome/stargaze

Makefile

Sets the `test` keyring backend for development

Set test keyring-backend for running dev node

---

x/stake/abci.go
x/stake/alias.go
x/stake/handler.go
x/stake/types/events.go

Fixes #17.
This should cover the basic events for the indexer to observe. Let me know if I missed anything!

Added stake events

---

x/curating/spec/README.md

Fixes #49.
Initial spec for the curating module. This will most likely change quite a bit as we iterate on the mechanic, but should provide a good foundation for moving forward with development.
NOTE: Will add #54 in another PR.

Added curating module spec (#49)

---

testdata/sim_app.go
x/curating/abci.go
x/curating/abci_test.go
x/curating/alias.go
x/curating/keeper/keeper.go
x/curating/keeper/post.go
x/curating/keeper/upvote.go
x/curating/keeper/upvote_test.go
x/curating/types/key.go

Quadratic voting redistribution (#55)

---

Makefile
app/app.go
app/export.go
cmd/staked/main.go
cmd/staked/testnet.go
docker/Dockerfile
go.sum

Adds improvements to the `staked testnet` and outputs a `docker-compose.yml` inlcuding the rest-server
usage:
```
staked testnet -o my-testnet --v 4
cd my-testnet
docker-compose up -d
```

tesnet cmd improvements

---

.drone.yml
.gitignore
README.md
contrib/go-test.sh

Setup codecov

---

x/curating/abci.go
x/curating/keeper/post.go
x/curating/keeper/upvote.go

Fixes a bug with Consensus Failure, see my comment on #75.

Delete expired posts and upvotes, closes #75

---

x/curating/abci.go
x/curating/abci_test.go
x/curating/keeper/reward_pool.go
x/curating/quadratic.go
x/curating/quadratic_test.go
x/curating/types/params.go

Fixes #54 
Added a new governance parameter for the max reward pool allocation for each curation. Right now it's 0.1% of the total reward pool.

Scale quadratic matching pool to not drain reward pool too fast

---

Makefile
app/app.go
contrib/ci/chains/stakebird.json
contrib/ci/setup-stakebird.sh
contrib/ibc/relayer/configs/stakebird-xfer/ibc1.json
docker/entry-point.sh
docker/test-entry-point.sh
testdata/sim_app.go
testdata/test_helpers.go
x/curating/abci_test.go
x/curating/keeper/post_test.go
x/curating/keeper/reward_pool_test.go
x/curating/keeper/upvote_test.go
x/curating/quadratic_test.go
x/curating/types/key.go
x/funding/client/cli/tx.go
x/funding/types/key.go

FUEL -> STB, closes #138

---

app/app.go
contrib/ci/setup-stakebird.sh
testdata/sim_app.go

Renamed address prefix to stb

---

contrib/ci/chains/stakebird.json
contrib/ci/setup-stakebird.sh
contrib/ibc/relayer/configs/stakebird-xfer/ibc1.json
docker/entry-point.sh
docker/test-entry-point.sh
testdata/test_helpers.go
x/curating/abci_test.go
x/curating/keeper/keeper.go
x/curating/keeper/upvote_test.go
x/curating/types/key.go
x/curating/types/params.go

Fixes #142. Fixes #141. 
This also enables paying gas in ATOM *or* STB.
This merge should trigger Dependabot on Stakebot and Stakewatcher.

Vote with ATOM

---

cmd/staked/testnet.go

add curation window param for testnet generation

---

x/curating/keeper/post.go
x/curating/keeper/post_test.go
x/curating/types/errors.go

Return error if post already exists

---

x/curating/abci_test.go
x/curating/genesis.go
x/curating/keeper/reward_pool.go
x/curating/keeper/reward_pool_test.go
x/curating/types/expected_keepers.go
x/curating/types/params.go

Initialize reward pool

---

x/curating/abci_test.go
x/curating/types/params.go

Reasoning:
* Voters are trading ATOM for STB, so they should get most of the reward
* Creators are not putting anything up except content
* This is similar to yEarn's strategy creators that get 5%

Updated creator reward to 5%

---

x/curating/abci.go
x/curating/abci_test.go
x/curating/keeper/post.go

Not deleting posts until theres a historical record

---

contrib/proto-installer.sh
proto/stakebird/curating/v1beta1/query.proto
x/curating/client/cli/cli.go
x/curating/client/cli/query.go
x/curating/keeper/grpc_query.go
x/curating/keeper/post.go
x/curating/types/keys.go
x/curating/types/query.pb.go
x/curating/types/query.pb.gw.go

Add query for posts by vendor

---

x/curating/client/cli/tx.go

Update curating tx cmd usage description

---

Makefile
cmd/staked/cmd/testnet.go
contrib/ci/setup-stakebird.sh
docker/entry-point.sh
docker/test-entry-point.sh
simapp/test_helpers.go
x/curating/abci_test.go
x/curating/keeper/upvote_test.go
x/curating/types/keys.go

Replaced uatom with ucredits

---

x/stake/keeper/stake.go

Will help in preventing https://github.com/public-awesome/stakebird/issues/256.

Perform delegation after stake

---

cmd/staked/cmd/testnet.go

rate: 5%
max_rate: 25%
max_change_rate: 5%

cmd/testnet: fix default commission rate

---

app/prefix.go
contrib/ci/chains/stakebird.json
contrib/ibc/relayer/configs/stakebird-xfer/ibc1.json
simapp/prefix.go
x/curating/abci_test.go

Fixes #271 
Must also fix https://github.com/public-awesome/stakebot/issues/271

Changed address prefix to stars

---

Makefile
x/curating/abci.go
x/curating/types/events.go

Need this data for the activity feed / notifications.
TODO

Add reward amounts to events

---

app/app.go

capability initialization on load latest only

---

.gitignore
Makefile
cmd/starsd/cmd/airdrop.go
cmd/starsd/cmd/genaccounts.go

Just a bit of cleanup and removed legacy Cosmos genesis support since we'll never need it.

Airdrop updates

---

cmd/starsd/cmd/genesis.go

* Update genesis time
* Enable sends

Updated genesis params

---

.drone.yml
.github/workflows/lint.yml
Dockerfile

wasmd v0.17 must be using v0.14

fix docker wasmvm version

---

cmd/starsd/cmd/testnet.go
go.mod
go.sum
x/alloc/types/params.go
x/claim/types/params.go
x/mint/types/params.go

update public-awesome/spm to fix cli output streams: fix `starsd export` being printed to cli even if using pipe

fix cli output 

---

.drone.yml
docker/Dockerfile.go-devtools
docker/Dockerfile.hermes
scripts/ci/upgrade/run-upgrade.sh
scripts/ci/upgrade/setup-preinstalled-stargaze.sh
testutil/watcher/main.go

This PR fixes an issue where the v1 process keeps running locking v2 access to the db and continue with the upgrade.

automated upgrade tests

---

go.mod
go.sum

- updates sdk version to v0.45.1
- updates spm version to set iavl cache

update sdk and spm version

---

.drone.yml
docker/Dockerfile.gaia

update integration test to latest gaia

---

cmd/starsd/main.go
scripts/wasm/upload-contracts.sh

Update contract versions for upload script

---

go.mod
go.sum

we are currently using our fork until changes are upstreamed.
https://github.com/public-awesome/wasmd/releases/tag/v0.27.0-stargaze.4

update wasmd dependency

---

app/ante.go
app/app.go
app/app_test.go
app/export.go
cmd/starsd/cmd/genesis.go
cmd/starsd/cmd/genwasm.go
cmd/starsd/cmd/start.go
cmd/starsd/cmd/testnet.go
internal/ante/min_commission.go
internal/ante/min_commission_test.go
internal/statesync/snapshotter.go
testutil/readiness-checker/main.go
testutil/simapp/simapp.go
testutil/watcher/main.go
x/alloc/client/cli/tx.go
x/alloc/client/cli/tx_create_vesting_account.go
x/alloc/keeper/keeper.go
x/alloc/keeper/keeper_test.go
x/alloc/types/params.go
x/claim/client/cli/query.go
x/claim/client/cli/tx.go
x/claim/keeper/claim_test.go
x/claim/keeper/hooks.go
x/claim/keeper/keeper.go
x/claim/keeper/keeper_test.go
x/mint/client/cli/query.go
x/mint/types/codec.go
x/mint/types/minter_test.go
x/mint/types/params.go

Gofumpt makes a bunch of boring formatting changes, that really rock, when used over time.

run gofumpt

---

x/alloc/genesis.go
x/alloc/keeper/grpc_query.go
x/alloc/keeper/params.go
x/alloc/module.go
x/alloc/types/genesis.go
x/claim/client/cli/query.go
x/claim/module.go

Fixing misnamed modules in code comments

Fixing some code comments 

---

go.mod
go.sum

Closes: #729
Details: https://github.com/tendermint/tendermint/issues/9972 and https://twitter.com/informalinc/status/1613580954383040512

Replacing tendermint/tendermint with the informalsystems fork

---

x/alloc/genesis.go
x/alloc/keeper/keeper.go

removing code used for genesis only

remove genesis fund community pool

---

x/alloc/README.md
x/mint/README.md

Mostly included governance params.

Added READMEs to modules

---

.drone.yml
app/upgrades.go
cmd/starsd/cmd/genesis.go
cmd/starsd/cmd/testnet.go
scripts/ci/hermes/config.toml
scripts/ci/upgrade/config.toml
scripts/ci/upgrade/proposal.sh
x/cron/abci.go
x/globalfee/client/cli/query.go
x/globalfee/client/cli/tx.go

Events are not propagated on success.

emit events to parent context

---

.github/workflows/interchaintest.yml
.github/workflows/interchaintest_custom_runner.yml
Makefile
e2e/setup.go

- Adds gh workflow to run PFM tests
- Remove heighliner dependency

[SG-885] Add gh action to run the PFM tests on PRs

---

.drone.yml
Dockerfile
Makefile
docker/Dockerfile.go-devtools

bump go version

---

.github/workflows/interchaintest.yml
Makefile
app/upgrades.go
e2e/chain_upgrade_test.go

- adding chain upgrade test
- adding pfm store to upgrade handler

ci: adding chain upgrade test to gh actions

---

go.mod
go.sum

updating ibc-go v7.3.0 to v7.3.1
https://github.com/cosmos/ibc-go/releases/tag/v7.3.1

bumping ibc-go
