- docs/stake.md
Fixes #3.
This wraps the Cosmos `x/staking` module, making delegations unbond after a certain period of time.
Storing delegations with a key tuple of `expire_time | post_id | stake_id` in a FIFO queue. 
`post_id`: tweet id
`stake_id`: auto-incrementing `uint64` for each like
This allows the end blocker to only peek the first element on each block. Then it can get all stakes for a post by iterating on `expire_time | post_id` , and pop each element when processed. So only currently active stakes are stored on chain.
It will be the duty of the the indexer to keep track of stake and tweet relationships long-term.
> Initial stake module specs

- .drone.yml
- app/app.go
- cmd/rocketd/init.go
- cmd/rocketd/tesnet.go
Made the unbonding period the same as the voting period to prevent users from not being able to stake due to funds being locked up. The default value can be set during chain init.
> Added default unbonding period of 72h to init genesis

- .gitattributes
Decided that it's better to keep proto generated files in version control so the repo can be navigated in Github, etc. Instead treat them as binary so they won't show up in diffs and won't have merge conflicts.
> Treating proto generated files as binary (#73)

- x/curating/keeper/post.go
- x/curating/keeper/upvote.go
Fixes #76.
The upvote gets created normally with a creator and deposit. The post doesn't have a creator and doesn't have a deposit.
> Make creator and deposit nil when no post exists (#76)

- .gitignore
- Makefile
- README.md
Better default make targets for working locally with multiple clients (like Stakebot), with a consistent keyring backend and chain id.
> Update local setup

- x/curating/quadratic.go
- x/curating/quadratic_test.go
If a post has zero votes, a `Division By Zero` error is currently thrown, this checks for that edge case in the `VoterReward` and `MatchReward` functions.
> Prevent divide by zero error, closes #130

- x/curating/types/params.go
This just makes local development much easier. The defaults will be set in the genesis file for testnets and mainnet anyway, not here.
> Changed default curation window to 10 mins

- app/app.go
Adds the following new governance proposal types:
* clear-contract-admin: Submit a clear admin for a contract to prevent further migrations proposal
* instantiate-contract:    Submit an instantiate wasm contract proposal
* migrate-contract:        Submit a migrate wasm contract to a new code version proposal
* set-contract-admin:      Submit a new admin for a contract proposal
* wasm-store:              Submit a wasm binary proposal
> Enable WASM proposals

- .drone.yml
- CHANGELOG.md
- Dockerfile
- app/upgrades.go
- cmd/starsd/cmd/genesis.go
- docs/static/openapi.yml
- go.mod
- scripts/ci/upgrade/proposal.sh
updates consensus mas gas param as part of the upgrade to handle cosmwasm
> update consensus and wasm params 

- cmd/starsd/main.go
current sdk version contains it's own rollback version which does tm rollback + sdk store rollback
> remove tm rollback command

- x/alloc/client/cli/query.go
Closes: #670 
Adds a cli cmd to the x/alloc module to retrieve the module params
> Add cli cmd to fetch x/alloc module to fetch params

- Dockerfile
- docker/Dockerfile.gaia
- docker/Dockerfile.icad
- docker/Dockerfile.osmosis
- docker/entry-point.sh
The launchpad integration tests should have the same max_gas param as mainnet to catch out of gas errors.
I also ran into errors building the docker images because of the go 1.19 requirement.
> Set block.max_gas in Docker entry-point.sh

- app/ante.go
- app/app.go
- internal/ante/min_deposit.go
- internal/ante/min_deposit_test.go
In the antehandler which checks for mininum deposit amount sent during `submit-proposal` the deposit token denom was hardcoded to `ustars`  (Ref: #712)
This causes issues when running the chain locally as the local instance has `stake` as the chain denom.
Changes in this PR include modification to the `MinDepositDecorator` antehandler to use the Deposit params from the gov keeper to get the denom name to check for the min-deposit value
> Removing token denom hardcoding in antehandler

- go.mod
- go.sum
Switches to https://github.com/public-awesome/wasmd/releases/tag/v0.30.1-stargaze to include a fix present in v0.31.0, it currently prevents proposal submissions.
> cli: fix wasmd store code proposal verification

- x/globalfee/README.md
- x/globalfee/spec/01_state.md
- x/globalfee/spec/02_messages.md
- x/globalfee/spec/03_ante_handlers.md
- x/globalfee/spec/04_events.md
- x/globalfee/spec/05_params.md
- x/globalfee/spec/06_client.md
- x/globalfee/spec/README.md
Ref: https://github.com/public-awesome/stargaze/issues/713
Includes the spec to implement the x/globalfees module
> docs: Spec for x/globalfee

- testutil/keeper/globalfee.go
- x/globalfee/client/cli/query.go
- x/globalfee/client/cli/tx.go
- x/globalfee/types/code_authorization.go
- x/globalfee/types/contract_authorization.go
- x/globalfee/types/keys.go
* Added the following cli tx
* set-code-authorization
* remove-code-authorization
* set-contract-authorization
* remove-contract-authorization 
* Added the following cli query
* params
* auth_by_code_id
* auth_by_contract_address
* auth_all
> feat(x/globalfee): Add cli queries and tx

- x/globalfee/client/cli/gov_tx.go
command tx flags should not be registered to governance commands because the main gov cmd will do it to the entire root.
> remove tx flags

- docker/entry-point.sh
* Set the following app parameters to new defaults, and allow them to be set with environment variables:
```
iavl-cache-size=1562500
simulation_gas_limit=50000000
query_gas_limit = 5000000
memory_cache_size=1000
```
> Set app.toml values in docker test image

- go.mod
- go.sum
This PR switches to our fork https://github.com/public-awesome/cosmos-sdk/releases/tag/v0.45.16-stargaze.2
Contains 2 fixes:
- Querying historical heights when a store wasn't present at the time
- Fixes pagination issues when querying txs in a block
> switch to sdk fork with upstream fixes

- Dockerfile
- cmd/starsd/cmd/start.go
- go.mod
- go.sum
- Updating go.mod
- Updating the dockerfile with checksum for new wasmvm version
> wasmd bump to v0.44.0

- testutil/simapp/simapp.go
- x/alloc/keeper/keeper_test.go
- x/cron/keeper/msg_server_test.go
- x/globalfee/ante/fee_setup_test.go
- x/globalfee/ante/fee_test.go
- x/globalfee/keeper/code_authorization_test.go
- x/globalfee/keeper/contract_authorization_test.go
- x/globalfee/keeper/msg_server_test.go
- x/tokenfactory/keeper/admins_test.go
- x/tokenfactory/keeper/create_denom_test.go
- x/tokenfactory/keeper/genesis_test.go
- x/tokenfactory/keeper/keeper_test.go
- x/tokenfactory/keeper/msg_server_test.go
> fixing linting errors 

- Makefile
- app/app.go
- proto/buf.gen.swagger.yaml
- scripts/protoc-swagger-gen.sh
With changing of proto works with new sdk, the existing swagger gen does not work.
Updated to fix it.
Using json instead of yaml as the `swagger-combine` output doesn't seem to work.
> fix: swagger generation for sdk47 proto

- cmd/starsd/cmd/settings.go
- x/globalfee/ante/fee.go
- x/globalfee/ante/fee_setup_test.go
- x/globalfee/ante/fee_test.go
* bump comet (#1203)
* globalfee: set gas restrictions
* update default settings
* add more test cases
* add test
> global fee impr (#1209)

- x/cron/abci.go
Events are automatically emitted back to the parent context on write/commit
> fix duplicated events
